name: ledesignduweb
description: "Gestion LDDW"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_gradient_colors: ^2.1.1
  gestures: ^1.0.0
  http: ^1.2.2
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/picto/robe.webp
    - assets/img/picto/chicetchoc2.jpg
    - assets/img/picto/trendyshopsac.jpg
    - assets/img/picto/Chemisehommeajustee.jpg
    - assets/img/picto/Chemisehomme.jpg
    - assets/img/picto/robe.webp
    - assets/img/picto/trendyshop.webp
    - assets/img/picto/find.png
    - assets/img/logo/logo.png
    - assets/img/logo/logo_transparent.png
    - assets/img/logo/logo.svg
    - assets/img/picto/share.png
    - assets/img/picto/like.png
    - assets/img/picto/home.png
    - assets/img/picto/add.png
    - assets/img/picto/message2.png
    - assets/img/picto/profil.png
